### ISSUE TITLE
Dataclasses python module is required

### ISSUE THREAD

**Issue by derekmulcahy** [pepijndevos/apicula#1]
I had to install the data classes python module to run dat19_h4x.py.

**Comment by pepijndevos** [comment]
Dataclasses were introduced in Python 3.7, so yea, not going to work out of the box on older versions.

https://docs.python.org/3/library/dataclasses.html

**Comment by derekmulcahy** [comment]
That explains it. I am running python 3.6.9 on Ubuntu 18.04.  It seems to work if I install the module.

Could you amend the instructions to indicate that the dataclasses module is also a requirement?

**Comment by pepijndevos** [comment]
Done.
