### ISSUE TITLE
openFPGALoader for JTAG config ?

### ISSUE THREAD

**Issue by Martoni** [pepijndevos/apicula#4]
Hi,
Have you tested openFPGALoader for SRAM configuration of bitstream ?
[It's seem's to be compatible ](https://github.com/trabucayre/openFPGALoader) with Gowin FPGA.

**Comment by pepijndevos** [comment]
No, I have not. Thanks for pointing it out. I'll test it after the holiday and update the instructions if it works. Also happy to hear the experience of anyone else who tried it.

On December 29, 2019 12:55:59 PM GMT+03:00, Fabien Marteau <notifications@github.com> wrote:
>Hi,
>Have you tested openFPGALoader for SRAM configuration of bitstream ?
>[It's seem's to be compatible
>](https://github.com/trabucayre/openFPGALoader) with Gowin FPGA.
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pepijndevos/apicula/issues/4

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by trabucayre** [comment]
Hi,
Just to complete Martoni's message: openFPGALoader is now able to write bitstream in flash.

**Comment by pepijndevos** [comment]
Cool, I tested it and updated the readme instructions. Hit a small issue, but it generally seems to work.

Have not yet tested it on Tang Nano, so I'll leave the vendor tool in there for now as an alternative.

**Comment by trabucayre** [comment]
Hi,
Tang Nano is WIP. I'm able to load bitstream to the SRAM but I've some hang when I try to write in flash.
Maybe I need to push current state with note about limitations.
Thank for the readme update
