### ISSUE TITLE
next-pnr python version does not match virtualenv version.

### ISSUE THREAD

**Issue by Martoni** [pepijndevos/apicula#7]
I'm using virtualenv version to use python 3.7 : 
```shell
$ source ~/pyenv/pyenv37/bin/activate
$ python --version
Python 3.7.5
```
But nextpnr use python 3.5 to run python script given in argument:
```shell
$  echo "import sys;print(sys.version)" > version.py
$ nextpnr-generic --run version.py 
3.5.3 (default, Sep 27 2018, 17:25:39) 
[GCC 6.3.0 20170516]
```
Is it a compile option for nextpnr ? Or can I change it with environment vars ?

3.5 is too old for executing simple.py script in fact (f-string problem).
```
 nextpnr-generic --pre-pack simple.py --pre-place simple_timing.py --json blinky.json --post-route bitstream.py --write pnrblinky.json
  File "simple.py", line 18
    with open(f"../{device}.pickle", 'rb') as f:
                                  ^
SyntaxError: invalid syntax
ERROR: Error occurred while executing Python script simple.py
0 warnings, 1 error
``` 

I keep trying, but if you have a clue ;)

**Comment by Martoni** [comment]
Solved ;)
But I had to change the CMakeList.txt of nextpnr project : 
```diff
diff --git a/CMakeLists.txt b/CMakeLists.txt
index 487db42..84a79c6 100644
--- a/CMakeLists.txt
+++ b/CMakeLists.txt
@@ -103,10 +103,10 @@ if (BUILD_GUI AND NOT BUILD_PYTHON)
     message(FATAL_ERROR "GUI requires Python to build")
 endif()
 
-find_package(PythonInterp 3.5 REQUIRED)
+find_package(PythonInterp 3.7 REQUIRED)
 if (BUILD_PYTHON)
     # TODO: sensible minimum Python version
-    find_package(PythonLibs 3.5 REQUIRED)
+    find_package(PythonLibs 3.7 REQUIRED)
 else()
     add_definitions("-DNO_PYTHON")
 endif()
```

And re-build/re-install nextpnr (don't forget to delete CMakeCache.txt before)

**Comment by Martoni** [comment]
But can't import numpy : 
```
$ nextpnr-generic --run version.py  -v --debug
Traceback (most recent call last):
  File "version.py", line 2, in <module>
    import numpy;
ModuleNotFoundError: No module named 'numpy'
ERROR: Error occurred while executing Python script version.py
0 warnings, 1 error
```

Ach, so close to my blinking LEDs ;)

**Comment by pepijndevos** [comment]
Nextpnr does not use the virtualenv, so you'll need to install numpy globally.

This definitely needs to be updated in the readme. (Or refactoring the generic script to have less requirements) Would gladly accept a PR.

On March 11, 2020 10:23:37 PM GMT+01:00, Fabien Marteau <notifications@github.com> wrote:
>But can't import numpy : 
>```
>$ nextpnr-generic --run version.py  -v --debug
>Traceback (most recent call last):
>  File "version.py", line 2, in <module>
>    import numpy;
>ModuleNotFoundError: No module named 'numpy'
>ERROR: Error occurred while executing Python script version.py
>0 warnings, 1 error
>```
>
>Ach, so close to my blinking LEDs ;)
>
>-- 
>You are receiving this because you are subscribed to this thread.
>Reply to this email directly or view it on GitHub:
>https://github.com/pepijndevos/apicula/issues/7#issuecomment-597885214

-- 
Sent from my Android device with K-9 Mail. Please excuse my brevity.

**Comment by Martoni** [comment]
ok my python3 installation is really fucked. In fact that works globally:
```
$ sudo python3 -m pip install numpy
```

Thanks
